name: 'SamsungAudioNotification'
packageKey: 'SamsungAudioNotification'
permissions:
  lan: {}
  discovery: {}
description: "Custom driver for testing audion notification"
vendorSupportInformation: "https://support.smartthings.com"
