name: Post duplicate profile comment
on:
  workflow_run:
    workflows: [Check for duplicate profiles]
    types:
      - completed

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Download comment artifact
        uses: actions/download-artifact@v3
        with:
          name: duplicate_profile_comment

      - name: Find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          body-includes: Duplicate profile check
          comment-author: 'github-actions[bot]'
          issue-number: ${{ github.event.number }}

      - name: Post comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-file: 'profile-comment-body.md'
          edit-mode: replace
          issue-number: ${{ github.event.number }}